// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdBg4prbt-Rg-YkmaHEVC1fYWK_bSXRbk',
    appId: '1:83156717699:web:e49469c81a2384cc74cbb6',
    messagingSenderId: '83156717699',
    projectId: 'tri13-c59c1',
    authDomain: 'tri13-c59c1.firebaseapp.com',
    storageBucket: 'tri13-c59c1.appspot.com',
    measurementId: 'G-NRH3NHKVH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoln9S3Bxwj7exPWEZXwQxOribe_wqW7U',
    appId: '1:83156717699:android:19389d7e5b4198b674cbb6',
    messagingSenderId: '83156717699',
    projectId: 'tri13-c59c1',
    storageBucket: 'tri13-c59c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__0N1-eBxd-cYYh-dupfCjgDt22TOv7Y',
    appId: '1:83156717699:ios:361df198db0675aa74cbb6',
    messagingSenderId: '83156717699',
    projectId: 'tri13-c59c1',
    storageBucket: 'tri13-c59c1.appspot.com',
    iosBundleId: 'com.example.tri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__0N1-eBxd-cYYh-dupfCjgDt22TOv7Y',
    appId: '1:83156717699:ios:361df198db0675aa74cbb6',
    messagingSenderId: '83156717699',
    projectId: 'tri13-c59c1',
    storageBucket: 'tri13-c59c1.appspot.com',
    iosBundleId: 'com.example.tri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdBg4prbt-Rg-YkmaHEVC1fYWK_bSXRbk',
    appId: '1:83156717699:web:6f32f9b2780e70bc74cbb6',
    messagingSenderId: '83156717699',
    projectId: 'tri13-c59c1',
    authDomain: 'tri13-c59c1.firebaseapp.com',
    storageBucket: 'tri13-c59c1.appspot.com',
    measurementId: 'G-WV8XZE6C6M',
  );
}
